### ISSUE TITLE
Possible simplification of the code

### ISSUE THREAD

**Issue by kbroman** [xiuyuma/DigitsCount#1]
The package looks great!

You might try something like the following, to simplify the code:

```r
f <- function(z) {
    ch <- as.character(z)
    ch <- gsub('[\\.0\\-]', '', ch)
    firstdig <- as.numeric(substr(ch, 1, 1))
    table( factor(firstdig, levels=1:9) )
}
```

**Comment by xiuyuma** [comment]
Dear Professor Broman


Thanks for your suggestion,  It is very convenient if we transferred the numerical data into character string first. I appreciate your help. I will revise the package and email you later.


Best Regards

Xiuyu Ma

________________________________
