### ISSUE TITLE
You just need to add a test or two

### ISSUE THREAD

**Issue by kbroman** [xiuyuma/DigitsCount#2]
Take a look at <http://kbroman.org/pkg_primer/pages/tests.html>

**Comment by xiuyuma** [comment]
Dear Professor Broman

Sorry to bother you, I am Xiuyu Ma a student in 826, I have updated my package, added test and modified function. https://github.com/xiuyuma/DigitsCount?

Best Regards
Xiuyu Ma




________________________________

**Comment by kbroman** [comment]
I made a few changes in [this pull request](https://github.com/xiuyuma/DigitsCount/pull/3), but with those, I think you're done.
